# version: '2'
version: '3'
services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      # - 8081:8081
      - 57018:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: q
      # ME_CONFIG_MONGODB_PORT: 57017
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    links:
      - mongo-db
    networks:
      - mongo-compose-network

  mongo-db:
    image: mongo:latest
    container_name: mongo-server
    environment:
    # https://stackoverflow.com/questions/47901561/how-to-run-mongodb-and-mongo-express-with-docker-compose
      MONGO_INITDB_DATABASE: demodb  

      MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: qq
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

      # MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      # MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

      # - ME_CONFIG_MONGODB_SERVER=mongo
      # - ME_CONFIG_MONGODB_PORT=27017
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      # - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      # - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      # - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      # - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      # - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}


    ports:
      - "57017:27017"
      # - "27017:27017"
    volumes:
      # - ./mongodb_data_container:/data/db
     - mongodb_data_container:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge

volumes:
 mongodb_data_container:
    